name: CD Pipeline (Stage)

on:
  push:
    branches: ["stage"]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: stage
