name: Deploy to AWS

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ vars.ROLE_ARN_TO_ASSUME }}
          role-session-name: deployrolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy build files to s3
        run: aws s3 cp ./build s3://${{ vars.BUCKET_NAME }} --recursive

      - name: Invalidate distribution cache
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.DISTRIBUTION_ID }} --paths "/*"
